export default {
  workspaces: {
    '.': {
      entry: ['src/main.tsx', 'src/server/index.ts', 'server.ts', 'vite.config.ts', 'vitest.config.ts'],
      project: ['src/**/*.{ts,tsx}', 'server.ts', 'vite.config.ts', 'vitest.config.ts', 'src/tests/**/*.{ts,tsx}'],
      ignore: [
        'src/server/scripts/migrate-to-brain.ts',
        'src/lib/prisma.ts',
        'src/lib/safe-logger.ts',
        'src/server/config/cors.ts',
        'src/lib/event-bus.ts',
        'src/lib/cognitive-metrics.ts',
        'src/lib/practice-recommendations.ts',
        'src/server/services/daily-trajectory.ts',
        'src/lib/storage-keys.ts',
        'src/hooks/useSocialEQEngine.ts',
        'src/hooks/useStorytellingEngine.ts',
        'src/hooks/useTopologyEngine.ts',
        'src/lib/anti-fraud.ts',
        'src/core/analyze-session/session-analysis.ts',
        'src/server/middleware/validate.ts',
        'src/server/utils/validation.ts',
        'src/server/utils/idea-status.ts',
        'src/lib/route-config.tsx',
        'src/server/schemas/neurotrainer.ts',
        'src/server/services/llm-provider.ts',
        'src/lib/practice-flow-analytics.ts',
        'src/core/events/event-schema.ts',
        'src/core/analyze-session/fixtures.ts',
        'src/server/schemas/feedback.ts',
        'apps/mobile/src/lib/practice-recommendations.ts',
        'src/lib/alphabet-table-generator.ts',
        'src/lib/frame-budget.ts',
        'src/lib/content-db.ts',
        'src/lib/cognitive-metrics.ts',
        'src/hooks/useAlphabetTableEngine.ts',
        'src/hooks/useNoiseReductionEngine.ts',
        'src/hooks/useNumericalEngine.ts',
        'src/lib/mentmath-generator.ts',
        'src/server/utils/privacy.ts',
        'src/lib/content-generator.ts',
        'src/lib/daily-practice-types.ts',
        'src/lib/socket.ts',
        'src/client/analytics/event-bus.ts',
        'src/server/events/event-bus.ts',
        'src/server/realtime/duels.ts',
        'src/server/services/analytics-persistence.ts',
        'src/lib/identity-vault.ts',
        'src/lib/storage-gateway.ts',
        'src/core/events/event-bus.ts',
        'src/lib/knowledge-base.ts',
        'src/hooks/useLanguageScannerEngine.ts',
        'src/hooks/useLogicalEngine.ts',
        'src/hooks/useLuscherEngine.ts',
        'src/hooks/useMentalMathEngine.ts',
        'src/hooks/useNBackEngine.ts',
        'src/server/services/neurotrainer.ts',
        'src/hooks/useRealityCheckEngine.ts',
        'src/hooks/useSchulteEngine.ts',
        'src/hooks/useSchulte90Engine.ts',
        'src/hooks/useSituationalEngine.ts',
        'src/hooks/useSpatialEngine.ts',
        'src/hooks/useStroopAlphabetEngine.ts',
        'src/hooks/useStroopEngine.ts',
        'src/server/services/telegram-notifier.ts',
        'src/hooks/useTypingEngine.ts',
        'src/hooks/useDispatcherEngine.ts',
        'src/hooks/useCollisionEngine.ts',
        'src/lib/content-generator.ts',
        'src/hooks/useDeepFocusEngine.ts',
        'src/hooks/useHypeFilterEngine.ts',
        'src/hooks/useReframingEngine.ts',
        'src/hooks/useRejectionImmunityEngine.ts',
        'src/lib/leagues.ts',
      ],
      ignoreDependencies: [
        '@capacitor/app',
        'capacitor-secure-storage-plugin',
        'expo-updates',
        'expo-system-ui',
        'build',
        'gradlew.bat',
        '@types/*',
        'vitest',
        '@vitest/*',
        '@playwright/test',
        '@testing-library/*',
        'jsdom',
        'tailwindcss',
        'typescript',
        'vite',
        'tsx',
        'prisma',
        'esbuild',
        'protobufjs',
      ],
    },
    'apps/capacitor': {
      entry: ['capacitor.config.ts'],
      project: ['**/*.{ts,tsx,json}'],
      ignore: ['android/**', 'ios/**', 'android/app/src/main/assets/public/**'],
      ignoreDependencies: ['build', 'gradlew.bat', '@capacitor/app', 'capacitor-secure-storage-plugin', 'expo-updates', 'expo-system-ui'],
    },
    'apps/mobile': {
      entry: ['app.json'],
      project: ['**/*.{ts,tsx,json}'],
    },
  },
  rules: {
    dependencies: 'error',
    devDependencies: 'error',
    exports: 'error',
    files: 'error',
    types: 'error',
  },
};
